# Generated by Django 2.1.2 on 2018-10-29 11:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181029_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalblocs',
            name='otherAcronyms',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regionalblocs',
            name='otherNames',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
