# Generated by Django 2.1.2 on 2018-10-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181029_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='iso639_2',
        ),
    ]
