# Generated by Django 2.1.2 on 2018-10-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_languages_iso639_2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='currencies',
            new_name='Currency',
        ),
        migrations.RenameModel(
            old_name='languages',
            new_name='Language',
        ),
        migrations.RenameModel(
            old_name='regionalBlocs',
            new_name='RegionalBloc',
        ),
    ]
