# Generated by Django 2.1.2 on 2018-10-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181029_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='alpha2Code',
            new_name='alpha2code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='alpha3Code',
            new_name='alpha3code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='altSpellings',
            new_name='alt_spellings',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='callingCodes',
            new_name='calling_codes',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='nativeName',
            new_name='native_name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='numericCode',
            new_name='numeric_code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='regionalBlocs',
            new_name='regional_blocs',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='topLevelDomain',
            new_name='top_level_domain',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='nativeName',
            new_name='native_name',
        ),
        migrations.RenameField(
            model_name='regionalbloc',
            old_name='otherAcronyms',
            new_name='other_acronyms',
        ),
        migrations.RenameField(
            model_name='regionalbloc',
            old_name='otherNames',
            new_name='other_names',
        ),
    ]
