# Generated by Django 2.1.2 on 2018-11-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181029_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='currencies',
        ),
        migrations.RemoveField(
            model_name='country',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='country',
            name='regional_blocs',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='RegionalBloc',
        ),
    ]
