# Generated by Django 2.1.2 on 2018-11-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20181106_0840'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='countries_visited', to='countries.Country'),
        ),
    ]
