# Generated by Django 2.1.2 on 2018-11-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20181106_0840'),
        ('users', '0003_auto_20181106_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_country', to='countries.Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='countries_list', to='countries.Country'),
        ),
    ]
