# Generated by Django 2.1.2 on 2018-11-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20181106_0840'),
        ('users', '0007_auto_20181111_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_country', to='countries.Country'),
        ),
    ]
