# Generated by Django 2.1.2 on 2018-11-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_country', to='countries.Country'),
        ),
    ]
