# Generated by Django 2.1.2 on 2018-11-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181113_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_country', to='countries.Country'),
        ),
    ]
