# Generated by Django 2.1.2 on 2018-10-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='gini',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
