# Generated by Django 2.1.2 on 2018-10-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181029_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='translations',
        ),
        migrations.DeleteModel(
            name='translations',
        ),
    ]
