# Generated by Django 2.1.2 on 2018-11-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table=None,
        ),
        migrations.AlterModelTable(
            name='currency',
            table=None,
        ),
        migrations.AlterModelTable(
            name='language',
            table=None,
        ),
        migrations.AlterModelTable(
            name='regionalbloc',
            table=None,
        ),
    ]
