# Generated by Django 2.1.2 on 2018-11-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20181106_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.URLField(null=True),
        ),
    ]
