# Generated by Django 2.1.2 on 2018-11-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_auto_20181114_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
    ]
