# Generated by Django 2.1.2 on 2018-11-06 07:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('top_level_domain', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('alpha2code', models.CharField(blank=True, max_length=255, null=True)),
                ('alpha3code', models.CharField(blank=True, max_length=255, null=True)),
                ('calling_codes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_spellings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('subregion', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('latlng', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('demonym', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('gini', models.FloatField(blank=True, null=True)),
                ('timezones', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('borders', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('native_name', models.CharField(blank=True, max_length=255, null=True)),
                ('numeric_code', models.CharField(blank=True, max_length=255, null=True)),
                ('flag', models.CharField(blank=True, max_length=255, null=True)),
                ('cioc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'api_country',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'api_currency',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso639_1', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('native_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'api_language',
            },
        ),
        migrations.CreateModel(
            name='RegionalBloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('other_acronyms', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('other_names', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_regionalbloc',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='currencies',
            field=models.ManyToManyField(to='countries.Currency'),
        ),
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(to='countries.Language'),
        ),
        migrations.AddField(
            model_name='country',
            name='regional_blocs',
            field=models.ManyToManyField(blank=True, to='countries.RegionalBloc'),
        ),
    ]
