# Generated by Django 2.1.2 on 2018-11-14 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20181111_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
