# Generated by Django 2.1.2 on 2018-11-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20181114_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripreport',
            name='date_updated',
        ),
    ]
