# Generated by Django 2.1.2 on 2018-11-23 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0008_tripreport_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='favoriters',
            field=models.ManyToManyField(related_name='favoriters', to=settings.AUTH_USER_MODEL),
        ),
    ]
