# Generated by Django 2.1.2 on 2018-11-28 08:58

from django.db import migrations, models
import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_tripreport_favoriters'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='image',
            field=models.ImageField(null=True, upload_to=trips.models.get_image_path),
        ),
    ]
