# Generated by Django 2.1.2 on 2018-11-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_tripreport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripreport',
            name='image',
            field=models.ImageField(null=True, upload_to='trip-report'),
        ),
    ]
