# Generated by Django 2.1.7 on 2019-07-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_auto_20181128_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripreport',
            name='image',
        ),
    ]
