# Generated by Django 2.1.2 on 2018-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='countries',
            field=models.ManyToManyField(blank=True, to='countries.Country'),
        ),
    ]
