# Generated by Django 2.1.2 on 2018-11-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181110_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='home_country',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
