# Generated by Django 2.1.2 on 2018-11-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='user_countries', to='countries.Country'),
        ),
    ]
